import { PropertyCategory, PropertyType, PropertyLayout } from './property.enums';

export const CATEGORY_TO_TYPES: Record<PropertyCategory, PropertyType[]> = {
  [PropertyCategory.COMMERCIAL_SALES]: [
    PropertyType.LABOR_CAMP,
    PropertyType.LAND,
    PropertyType.OFFICE_SPACE,
    PropertyType.RETAIL_SPACE,
    PropertyType.VILLA,
    PropertyType.WAREHOUSE,
    PropertyType.WHOLE_BUILDING,
    PropertyType.WHOLE_COMPOUND,
  ],
  [PropertyCategory.COMMERCIAL_LEASING]: [
    PropertyType.LABOR_CAMP,
    PropertyType.LAND,
    PropertyType.OFFICE_SPACE,
    PropertyType.RETAIL_SPACE,
    PropertyType.VILLA,
    PropertyType.WAREHOUSE,
    PropertyType.WHOLE_BUILDING,
    PropertyType.WHOLE_COMPOUND,
  ],
  [PropertyCategory.RESIDENTIAL_LEASING]: [
    PropertyType.APARTMENT,
    PropertyType.COMPOUND_VILLA,
    PropertyType.LAND,
    PropertyType.PENTHOUSE,
    PropertyType.STAND_ALONE_VILLA,
    PropertyType.TOWNHOUSE,
    PropertyType.WHOLE_BUILDING,
    PropertyType.WHOLE_COMPOUND,
  ],
  [PropertyCategory.RESIDENTIAL_SALES]: [
    PropertyType.APARTMENT,
    PropertyType.COMPOUND_VILLA,
    PropertyType.LAND,
    PropertyType.PENTHOUSE,
    PropertyType.STAND_ALONE_VILLA,
    PropertyType.TOWNHOUSE,
    PropertyType.WHOLE_BUILDING,
    PropertyType.WHOLE_COMPOUND,
  ],
};

export const TYPE_TO_LAYOUTS: Record<PropertyType, PropertyLayout[]> = {
  [PropertyType.LAND]: [PropertyLayout.SQM_SPACE],
  [PropertyType.LABOR_CAMP]: [PropertyLayout.SQM_SPACE],
  [PropertyType.OFFICE_SPACE]: [PropertyLayout.SQM_SPACE],
  [PropertyType.RETAIL_SPACE]: [PropertyLayout.SQM_SPACE],
  [PropertyType.WAREHOUSE]: [PropertyLayout.SQM_SPACE],
  [PropertyType.WHOLE_BUILDING]: [
    PropertyLayout.STUDIO,
    PropertyLayout.ONE_BR,
    PropertyLayout.TWO_BR,
    PropertyLayout.THREE_BR,
    PropertyLayout.FOUR_BR,
    PropertyLayout.FIVE_BR,
    PropertyLayout.MIXED,
  ],
  [PropertyType.WHOLE_COMPOUND]: [
    PropertyLayout.STUDIO,
    PropertyLayout.ONE_BR,
    PropertyLayout.TWO_BR,
    PropertyLayout.THREE_BR,
    PropertyLayout.FOUR_BR,
    PropertyLayout.FIVE_BR,
    PropertyLayout.SIX_BR,
    PropertyLayout.SEVEN_BR,
    PropertyLayout.EIGHT_BR,
    PropertyLayout.NINE_BR,
    PropertyLayout.TEN_BR,
    PropertyLayout.PLUS_TEN_BR,
    PropertyLayout.MIXED,
  ],
  [PropertyType.APARTMENT]: [
    PropertyLayout.STUDIO,
    PropertyLayout.ONE_BR,
    PropertyLayout.TWO_BR,
    PropertyLayout.THREE_BR,
    PropertyLayout.FOUR_BR,
    PropertyLayout.FIVE_BR,
  ],
  [PropertyType.COMPOUND_VILLA]: [
    PropertyLayout.ONE_BR,
    PropertyLayout.TWO_BR,
    PropertyLayout.THREE_BR,
    PropertyLayout.FOUR_BR,
    PropertyLayout.FIVE_BR,
    PropertyLayout.SIX_BR,
    PropertyLayout.SEVEN_BR,
    PropertyLayout.EIGHT_BR,
    PropertyLayout.NINE_BR,
    PropertyLayout.TEN_BR,
    PropertyLayout.PLUS_TEN_BR,
  ],
  [PropertyType.PENTHOUSE]: [
    PropertyLayout.ONE_BR,
    PropertyLayout.TWO_BR,
    PropertyLayout.THREE_BR,
    PropertyLayout.FOUR_BR,
    PropertyLayout.FIVE_BR,
    PropertyLayout.SIX_BR,
    PropertyLayout.SEVEN_BR,
    PropertyLayout.EIGHT_BR,
    PropertyLayout.NINE_BR,
    PropertyLayout.TEN_BR,
    PropertyLayout.PLUS_TEN_BR,
  ],
  [PropertyType.STAND_ALONE_VILLA]: [
    PropertyLayout.ONE_BR,
    PropertyLayout.TWO_BR,
    PropertyLayout.THREE_BR,
    PropertyLayout.FOUR_BR,
    PropertyLayout.FIVE_BR,
    PropertyLayout.SIX_BR,
    PropertyLayout.SEVEN_BR,
    PropertyLayout.EIGHT_BR,
    PropertyLayout.NINE_BR,
    PropertyLayout.TEN_BR,
    PropertyLayout.PLUS_TEN_BR,
  ],
  [PropertyType.TOWNHOUSE]: [
    PropertyLayout.ONE_BR,
    PropertyLayout.TWO_BR,
    PropertyLayout.THREE_BR,
    PropertyLayout.FOUR_BR,
    PropertyLayout.FIVE_BR,
    PropertyLayout.SIX_BR,
    PropertyLayout.SEVEN_BR,
    PropertyLayout.EIGHT_BR,
    PropertyLayout.NINE_BR,
    PropertyLayout.TEN_BR,
    PropertyLayout.PLUS_TEN_BR,
  ],
  [PropertyType.VILLA]: [
    PropertyLayout.ONE_BR,
    PropertyLayout.TWO_BR,
    PropertyLayout.THREE_BR,
    PropertyLayout.FOUR_BR,
    PropertyLayout.FIVE_BR,
    PropertyLayout.SIX_BR,
    PropertyLayout.SEVEN_BR,
    PropertyLayout.EIGHT_BR,
    PropertyLayout.NINE_BR,
    PropertyLayout.TEN_BR,
    PropertyLayout.PLUS_TEN_BR,
  ],
};