export const QATAR_LOCATIONS = [
  'Aamra - Al Wakra',
  'Abal Halayem - Al Rayyan',
  'Abal Jahazel - Al Sheehaniya',
  'Abu Dhalouf - Al Shamal',
  'Abu Hamour - Al Rayyan',
  'Abu Samra - Al Rayyan',
  'Abu Sidra - Al Rayyan',
  'Afjan - Al Sheehaniya',
  'Ain Khaled - Al Rayyan',
  'Ain Sinan - Al Shamal',
  'Al Afja - Al Wakra',
  'Al Areesh - Al Shamal',
  'Al Aziziya - Al Rayyan',
  'Al Bidda - Doha',
  'Al Dafna - Doha',
  'Al Daiha - Al Wakra',
  'Al Dakheera - Al Khor',
  'Al Deainiyat - Al Rayyan',
  'Al Ebb - Al Daayen',
  'Al Edaid Base - Al Rayyan',
  'Al Egla - Al Daayen',
  'Al Froosh - Umm Salal',
  'Al Gaeyya - Al Sheehaniya',
  'Al Galayel - Al Rayyan',
  'Al Garayen - Al Rayyan',
  'Al Gassar - Doha',
  'Al Ghariya - Al Shamal',
  'Al Ghanim Al Jadeed - Al Rayyan',
  'Al Hamla - Al Sheehaniya',
  'Al Hawafer - Al Sheehaniya',
  'Al Hemaila - Al Rayyan',
  'Al Hilal - Doha',
  'Al Hitmi - Doha',
  'Al Jasra - Doha',
  'Al Jelaiat - Al Rayyan',
  'Al Jemailiya - Al Sheehaniya',
  'Al Jeryan - Al Daayen',
  'Al Karaana - Al Rayyan',
  'Al Khaldiya - Al Rayyan',
  'Al Kharaitiyat - Umm Salal',
  'Al Kharayej - Lusail',
  'Al Kharrara - Al Wakra',
  'Al Kheesa - Al Daayen',
  'Al Khor City - Al Khor',
  'Al Khulaifat - Doha',
  'Al Luqta - Al Daayen',
  'Al Luqta - Al Rayyan',
  'Al Maamoura - Doha',
  'Al Manaseer - Al Rayyan',
  'Al Mansoura - Doha',
  'Al Markhiya - Doha',
  'Al Marroona - Al Shamal',
  'Al Masrouhiya - Al Daayen',
  'Al Mashaf - Al Wakra',
  'Al Mearad - Al Rayyan',
  'Al Messila - Doha',
  'Al Metfardat - Al Wakra',
  'Al Mirqab - Doha',
  'Al Mirqab Al Jadeed - Doha',
  'Al Muntazah - Doha',
  'Al Murra - Al Rayyan',
  'Al Najada - Doha',
  'Al Nasr - Doha',
  'Al Nasraniya - Al Rayyan',
  'Al Nehaidan - Al Wakra',
  'Al Nigyan - Al Wakra',
  'Al Rehayya - Al Daayen',
  'Al Rekayya - Al Rayyan',
  'Al Ruffaa - Doha',
  'Al Rumaila - Doha',
  'Al Ruwaidat - Al Sheehaniya',
  'Al Sadd - Doha',
  'Al Sailiya - Al Rayyan',
  'Al Sakhama - Al Daayen',
  'Al Seej - Al Rayyan',
  'Al Shabhana - Al Sheehaniya',
  'Al Shaqab - Al Rayyan',
  'Al Sheehaniya - Al Sheehaniya',
  'Al Sidari - Al Wakra',
  'Al Slemiya - Al Rayyan',
  'Al Souq (Souq Waqif) - Doha',
  'Al Tarfa - Doha',
  'Al Themaid - Al Rayyan',
  'Al Thumama - Doha',
  'Al Waab - Al Rayyan',
  'Al Wajba - Al Rayyan',
  'Al Wakra - Al Wakra',
  'Al Wukair - Al Wakra',
  'Al Zeghain - Al Sheehaniya',
  'Al Zubara - Al Shamal',
  'Aspire Zone - Al Rayyan',
  'Atran - Al Sheehaniya',
  'Baaya - Al Rayyan',
  'Bani Hajer - Al Rayyan',
  'Barahat Al Jufairi - Doha',
  'Barga Al Hamil - Al Rayyan',
  'Barga Al Kharaz - Al Rayyan',
  'Barga Egaif - Al Sheehaniya',
  'Barwa City - Al Rayyan',
  'Birkat Al Awamer - Al Wakra',
  'Broog - Al Sheehaniya',
  'Bu Fessela - Umm Salal',
  'Bu Garn - Al Sheehaniya',
  'Bu Garn - Umm Salal',
  'Bu Ghawlana - Al Sheehaniya',
  'Bu Glaila - Umm Salal',
  'Bu Kheesa - Al Sheehaniya',
  'Bu Traifa - Al Sheehaniya',
  'Dahl Al Hamam - Doha',
  'Doha Al Jadeeda - Doha',
  'Doha Port - Doha',
  'Duhail - Doha',
  'Dukhan - Al Sheehaniya',
  'Education City - Al Rayyan',
  'Eglat Faisal - Al Rayyan',
  'Eglat Zuwayyed - Al Wakra',
  'Erkyah - Lusail',
  'Fereej Abdel Aziz - Doha',
  'Fereej Al Ali - Doha',
  'Fereej Al Amir - Al Rayyan',
  'Fereej Al Asiri - Al Rayyan',
  'Fereej Al Asmakh - Doha',
  'Fereej Al Manaseer - Al Rayyan',
  'Fereej Al Murra - Al Rayyan',
  'Fereej Al Soudan - Al Rayyan',
  'Fereej Al Zaeem - Al Rayyan',
  'Fereej Bin Dirhem - Doha',
  'Fereej Bin Mahmoud - Doha',
  'Fereej Bin Omran - Doha',
  'Fereej Kulaib - Doha',
  'Floresta Gardens - The Pearl',
  'Fox Hills - Lusail',
  'Fuwairit - Al Shamal',
  'Getna - Al Sheehaniya',
  'Gewan Island - The Pearl',
  'Gharaffat Al Rayyan - Al Rayyan',
  'Gharaf Al Thawr - Al Rayyan',
  'Ghasham - Al Wakra',
  'Giardino - The Pearl',
  'Hamad International Airport - Doha',
  'Hamad Medical City - Doha',
  'Hazm Al Markhiya - Doha',
  'Huzoom - Lusail',
  'Imlaih - Al Rayyan',
  'Industrial Area - Al Khor',
  'Industrial Area - Doha',
  'Izghawa - Doha',
  'Jabal Marmi - Al Wakra',
  'Jabal Thuaileb - Al Daayen',
  'Jaww Al Kharaz - Al Rayyan',
  'Jelaiah - Al Rayyan',
  'Jeryan Al Reyoog - Al Rayyan',
  'Jeryan Jenaihat - Al Daayen',
  'Jeryan Nejaima - Doha',
  'Jery Al Dabi - Al Rayyan',
  'Jery Al Matrooshi - Al Daayen',
  'Jery Khabbab - Umm Salal',
  'Katara Cultural Village - Doha',
  'Khor Al Udaid - Al Wakra',
  'La Plage - The Pearl',
  'Leabaib - Al Daayen',
  'Learagg - Al Rayyan',
  'Leashara - Al Rayyan',
  'Leatooriya - Al Sheehaniya',
  'Lebday - Al Rayyan',
  'Lebsayyer - Al Sheehaniya',
  'Lebyatiya - Al Sheehaniya',
  'Legsaira - Al Wakra',
  'Legtaifiya - Doha',
  'Lekhoos - Al Wakra',
  'Lekhwair - Doha',
  'Leshaiger - Al Wakra',
  'Lewaija - Al Khor',
  'Leghraifa - Al Khor',
  'Luaib - Al Rayyan',
  'Lusail District',
  'Lusail Marina - Lusail',
  'Lusail Waterfront - Lusail',
  'Madina Centrale - The Pearl',
  'Madinat Al Kaaban - Al Shamal',
  'Madinat Al Shamal - Al Shamal',
  'Madinat Khalifa North - Doha',
  'Madinat Khalifa South - Doha',
  'Mebaireek - Al Rayyan',
  'Mehairja - Al Rayyan',
  'Mekaines - Al Rayyan',
  'Mesaieed - Al Wakra',
  'Mesaieed Free Zone - Al Wakra',
  'Mesaieed Industrial Area - Al Wakra',
  'Mesaigra - Al Wakra',
  'Mesaimeer - Al Rayyan',
  'Msheireb - Doha',
  'Muaither - Al Rayyan',
  'Muaither Al Wukair - Al Wakra',
  'Muraikh - Al Rayyan',
  'Najma - Doha',
  'Nega Al Fagara - Al Wakra',
  'Negyan Al Sada - Al Wakra',
  'New Al Hitmi - Doha',
  'New Al Rayyan - Al Rayyan',
  'New Fereej Al Khulaifat - Al Rayyan',
  'New Industrial Area - Al Rayyan',
  'New Salata - Doha',
  'Nuaija - Doha',
  'Old Airport - Doha',
  'Old Al Ghanim - Doha',
  'Old Al Rayyan - Doha',
  'Old Salata - Doha',
  'Onaiza - Doha',
  'Porto Arabia - The Pearl',
  'Qanat Quartier - The Pearl',
  'Qetaifan Island - Lusail',
  'QNCC - Al Rayyan',
  'Ras Bu Abboud - Doha',
  'Ras Bu Fontas - Al Wakra',
  'Ras Laffan - Al Khor',
  'Rasheeda - Al Khor',
  'Rawdat Abal Heeran - Al Rayyan',
  'Rawdat Al Faras - Al Khor',
  'Rawdat Al Faras - Al Rayyan',
  'Rawdat Al Hamama - Al Daayen',
  'Rawdat Al Jahhaniya - Al Rayyan',
  'Rawdat Al Khail - Doha',
  'Rawdat Egdaim - Al Rayyan',
  'Rawdat Hawtan - Al Khor',
  'Rawdat Ishala - Al Rayyan',
  'Rawdat Kharja - Al Sheehaniya',
  'Ruwais - Al Shamal',
  'Sabina - Al Rayyan',
  'Sawda Natheel - Al Rayyan',
  'Sealine - Al Wakra',
  'Semaisma - Al Daayen',
  'Shagra - Al Wakra',
  'Shariya - Al Rayyan',
  'Snay Lehmaidi - Umm Salal',
  'Tenbek - Al Daayen',
  'The Pearl - Doha',
  'The Pearl Island',
  'The Seef - Lusail',
  'Tharb - Al Rayyan',
  'Traina - Al Wakra',
  'Umm Ain - Al Rayyan',
  'Umm Al Amad - Umm Salal',
  'Umm Al Dayyat - Al Sheehaniya',
  'Umm Al March - Al Rayyan',
  'Umm Al Seneem - Al Rayyan',
  'Umm Bab - Al Sheehaniya',
  'Umm Besher - Al Wakra',
  'Umm Birkah - Al Khor',
  'Umm Ebairiya - Umm Salal',
  'Umm Ejwaifa - Al Khor',
  'Umm Garn - Al Daayen',
  'Umm Ghuwailina - Doha',
  'Umm Jarra - Al Rayyan',
  'Umm Juwashen - Al Rayyan',
  'Umm Leghab - Al Sheehaniya',
  'Umm Lekhba - Doha',
  'Umm Lekhya - Al Sheehaniya',
  'Umm Salal Ali - Umm Salal',
  'Umm Salal Mohammed - Umm Salal',
  'Umm Samra - Al Sheehaniya',
  'Umm Saneem - Doha',
  'Umm Shubrum - Al Rayyan',
  'Umm Sidra - Al Sheehaniya',
  'Umm Wadi - Al Sheehaniya',
  'Umm Zubar West - Al Sheehaniya',
  'Viva Bahriya - The Pearl',
  'Wadi Aba Seleel - Al Wakra',
  'Wadi Abal Gherban - Al Wakra',
  'Wadi Al Banat - Al Daayen',
  'Wadi Al Ewaira - Al Daayen',
  'Wadi Al Jinh - Al Rayyan',
  'Wadi Al Sail - Doha',
  'Wadi Al Wasah - Al Daayen',
  'Wadi Jallal - Al Wakra',
  'Wadi Laswag - Al Sheehaniya',
  'West Bay - Doha',
  'West Bay Lagoon - Doha',
  'Wholesale Market - Doha',
];
