export const PROPERTY_SEED_COUNT = 120;

import { CategoryKind } from '@prisma/client';

export const CATEGORIES: { name: string; kind: CategoryKind }[] = [
  { name: 'Commercial Leasing', kind: CategoryKind.RENT },
  { name: 'Commercial Sales', kind: CategoryKind.SALE },
  { name: 'Residential Leasing', kind: CategoryKind.RENT },
  { name: 'Residential Sales', kind: CategoryKind.SALE },
];

export const TYPES = [
  'Apartment',
  'Compound Villa',
  'Labor Camp',
  'Land',
  'Office Space',
  'Penthouse',
  'Retail Space',
  'Standalone Villa',
  'Townhouse',
  'Villa',
  'Villa Partition',
  'Warehouse',
  'Whole Building',
  'Whole Compound',
];

export const LAYOUTS = [
  '1BR',
  '2BR',
  '3BR',
  '4BR',
  '5BR',
  '6BR',
  '7BR',
  '8BR',
  '9BR',
  '10BR+',
  'Studio',
  'Mixed',
  'SQM SPACE',
];

export const FURNISHINGS = [
  'Fitted - Furnished',
  'Fitted - Semi Furnished',
  'Fitted - Unfurnished',
  'Mixed',
  'Shell & Core',
];

export const UTILITIES = [
  'Water & Electricity',
  'Internet',
  'District Cooling',
  'Service Charge',
  'Sewage',
];

export const FACILITIES = [
  'Basketball Court',
  'BBQ Area',
  'Catering Service',
  'Cinema',
  'Cleaning Service',
  'Clubhouse',
  'Co-working Space',
  'Football Court',
  'Gym',
  'Jacuzzi',
  "Kid's Play Area",
  'Laundry Service',
  'Mosque',
  'Multi Purpose Hall',
  'Padel Court',
  'Private Pool',
  'Sauna',
  'Shared Pool',
  'Squash Court',
  'Steam Room',
  'Tennis Court',
];

export const CATEGORY_TYPE_RELATIONS: Record<string, string[]> = {
  'Commercial Leasing': [
    'Labor Camp',
    'Land',
    'Office Space',
    'Retail Space',
    'Villa',
    'Warehouse',
    'Whole Building',
    'Whole Compound',
  ],
  'Commercial Sales': [
    'Labor Camp',
    'Land',
    'Office Space',
    'Retail Space',
    'Villa',
    'Warehouse',
    'Whole Building',
    'Whole Compound',
  ],
  'Residential Leasing': [
    'Apartment',
    'Compound Villa',
    'Land',
    'Penthouse',
    'Standalone Villa',
    'Townhouse',
    'Villa Partition',
    'Whole Building',
  ],
  'Residential Sales': [
    'Apartment',
    'Compound Villa',
    'Land',
    'Penthouse',
    'Standalone Villa',
    'Townhouse',
    'Villa Partition',
    'Whole Building',
  ],
};

export const TYPE_LAYOUT_RELATIONS: Record<string, string[]> = {
  Apartment: ['1BR', '2BR', '3BR', '4BR', 'Studio'],
  'Compound Villa': [
    '2BR',
    '3BR',
    '4BR',
    '5BR',
    '6BR',
    '7BR',
    '8BR',
    '9BR',
    '10BR+',
  ],
  Land: ['SQM SPACE'],
  'Labor Camp': ['SQM SPACE', 'Mixed'],
  'Office Space': ['SQM SPACE', 'Mixed'],
  'Retail Space': ['SQM SPACE', 'Mixed'],
  Warehouse: ['SQM SPACE', 'Mixed'],
  'Whole Building': ['Mixed', 'SQM SPACE'],
  'Whole Compound': [
    '2BR',
    '3BR',
    '4BR',
    '5BR',
    '6BR',
    '7BR',
    '8BR',
    '9BR',
    '10BR+',
    'Mixed',
  ],
  Penthouse: [
    '1BR',
    '2BR',
    '3BR',
    '4BR',
    '5BR',
    '6BR',
    '7BR',
    '8BR',
    '9BR',
    '10BR+',
  ],
  'Standalone Villa': [
    '1BR',
    '2BR',
    '3BR',
    '4BR',
    '5BR',
    '6BR',
    '7BR',
    '8BR',
    '9BR',
    '10BR+',
  ],
  Townhouse: ['1BR', '2BR', '3BR', '4BR', 'Mixed', 'Studio'],
  Villa: ['2BR', '3BR', '4BR', '5BR', '6BR', '7BR', '8BR', '9BR', '10BR+'],
  'Villa Partition': ['1BR', '2BR', '3BR', 'Studio'],
};
